"""SQLite persistence — jobs, applications, and the answer cache.

FROZEN schema (SPEC.md §6, §9): do NOT edit this file from a feature branch.
Workstreams read/write via the typed helpers here; schema changes go through an
interface PR all branches rebase on.

Tables
------
jobs         one row per SimplifyJobs listing (dedupe key = feed ``id``)
applications one row per application attempt (dedupe key = job_id)
answers      cached free-text LLM answers (dedupe key = question_hash + company)
"""

from __future__ import annotations

import sqlite3
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path

SCHEMA = """
CREATE TABLE IF NOT EXISTS jobs (
    id            TEXT PRIMARY KEY,          -- SimplifyJobs feed UUID
    company_name  TEXT NOT NULL,
    title         TEXT NOT NULL,
    url           TEXT NOT NULL,             -- raw feed url
    final_url     TEXT,                      -- resolved ATS url (after redirects)
    ats           TEXT,                      -- ATSKind value
    category      TEXT,
    locations     TEXT,                      -- JSON-encoded list[str]
    sponsorship   TEXT,
    active        INTEGER NOT NULL DEFAULT 1,
    is_visible    INTEGER NOT NULL DEFAULT 1,
    score         INTEGER NOT NULL DEFAULT 0,
    date_posted   INTEGER,                   -- unix epoch from feed
    first_seen    TEXT NOT NULL,             -- ISO8601
    last_seen     TEXT NOT NULL,             -- ISO8601
    status        TEXT NOT NULL DEFAULT 'new'  -- new|changed|inactive
);

CREATE TABLE IF NOT EXISTS applications (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id        TEXT NOT NULL UNIQUE REFERENCES jobs(id),
    status        TEXT NOT NULL DEFAULT 'queued',  -- see SPEC §6 status set
    filled_at     TEXT,
    submitted_at  TEXT,
    screenshot    TEXT,
    notes         TEXT
);

CREATE TABLE IF NOT EXISTS answers (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    question_hash TEXT NOT NULL,
    company       TEXT NOT NULL,
    question      TEXT NOT NULL,
    answer        TEXT NOT NULL,
    created_at    TEXT NOT NULL,
    edited_at     TEXT,
    UNIQUE(question_hash, company)
);

CREATE INDEX IF NOT EXISTS idx_jobs_score ON jobs(score DESC);
CREATE INDEX IF NOT EXISTS idx_apps_status ON applications(status);
"""

#: Valid application statuses (SPEC.md §6).
APP_STATUSES = frozenset(
    {"queued", "filled", "needs_input", "submitted", "failed", "manual", "skipped"}
)


@dataclass(slots=True)
class JobRow:
    """A row from ``jobs``. ``locations`` is decoded to a list here."""

    id: str
    company_name: str
    title: str
    url: str
    final_url: str | None
    ats: str | None
    category: str | None
    locations: list[str]
    sponsorship: str | None
    active: bool
    is_visible: bool
    score: int
    date_posted: int | None
    status: str


def connect(db_path: str | Path) -> sqlite3.Connection:
    """Open a connection with row factory and foreign keys enabled, creating schema."""
    Path(db_path).parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    conn.executescript(SCHEMA)
    return conn


@contextmanager
def transaction(conn: sqlite3.Connection) -> Iterator[sqlite3.Connection]:
    """Commit on success, roll back on error."""
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise


# ---- jobs -----------------------------------------------------------------


def upsert_job(
    conn: sqlite3.Connection,
    *,
    id: str,
    company_name: str,
    title: str,
    url: str,
    now_iso: str,
    final_url: str | None = None,
    ats: str | None = None,
    category: str | None = None,
    locations_json: str | None = None,
    sponsorship: str | None = None,
    active: bool = True,
    is_visible: bool = True,
    score: int = 0,
    date_posted: int | None = None,
) -> str:
    """Insert or update a job by feed ``id``. Idempotent.

    Returns the row status: ``"new"`` for a first insert, ``"changed"`` when a
    material field differs from the stored row, else ``"unchanged"``. Preserves
    ``first_seen`` across updates and always refreshes ``last_seen``.
    """
    cur = conn.execute("SELECT * FROM jobs WHERE id = ?", (id,))
    existing = cur.fetchone()
    if existing is None:
        conn.execute(
            """INSERT INTO jobs (id, company_name, title, url, final_url, ats, category,
                locations, sponsorship, active, is_visible, score, date_posted,
                first_seen, last_seen, status)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            (
                id, company_name, title, url, final_url, ats, category,
                locations_json, sponsorship, int(active), int(is_visible), score,
                date_posted, now_iso, now_iso, "new",
            ),
        )
        return "new"

    changed = (
        existing["title"] != title
        or existing["final_url"] != final_url
        or bool(existing["active"]) != active
        or bool(existing["is_visible"]) != is_visible
        or existing["score"] != score
    )
    status = "changed" if changed else "unchanged"
    conn.execute(
        """UPDATE jobs SET company_name=?, title=?, url=?, final_url=?, ats=?, category=?,
            locations=?, sponsorship=?, active=?, is_visible=?, score=?, date_posted=?,
            last_seen=?, status=? WHERE id=?""",
        (
            company_name, title, url, final_url, ats, category, locations_json,
            sponsorship, int(active), int(is_visible), score, date_posted,
            now_iso, status if changed else existing["status"], id,
        ),
    )
    return status


def mark_inactive_absent(conn: sqlite3.Connection, seen_ids: set[str], now_iso: str) -> int:
    """Mark jobs not present in ``seen_ids`` as inactive. Returns count updated."""
    cur = conn.execute("SELECT id FROM jobs WHERE active = 1")
    stale = [r["id"] for r in cur.fetchall() if r["id"] not in seen_ids]
    for jid in stale:
        conn.execute(
            "UPDATE jobs SET active=0, status='inactive', last_seen=? WHERE id=?",
            (now_iso, jid),
        )
    return len(stale)


def _to_jobrow(row: sqlite3.Row) -> JobRow:
    import json

    return JobRow(
        id=row["id"],
        company_name=row["company_name"],
        title=row["title"],
        url=row["url"],
        final_url=row["final_url"],
        ats=row["ats"],
        category=row["category"],
        locations=json.loads(row["locations"]) if row["locations"] else [],
        sponsorship=row["sponsorship"],
        active=bool(row["active"]),
        is_visible=bool(row["is_visible"]),
        score=row["score"],
        date_posted=row["date_posted"],
        status=row["status"],
    )


def list_jobs(
    conn: sqlite3.Connection,
    *,
    min_score: int = 0,
    active_only: bool = True,
    limit: int | None = None,
) -> list[JobRow]:
    """Return scored jobs ordered by score desc."""
    q = "SELECT * FROM jobs WHERE score >= ?"
    params: list[object] = [min_score]
    if active_only:
        q += " AND active = 1 AND is_visible = 1"
    q += " ORDER BY score DESC, date_posted DESC"
    if limit is not None:
        q += " LIMIT ?"
        params.append(limit)
    return [_to_jobrow(r) for r in conn.execute(q, params).fetchall()]


def get_job(conn: sqlite3.Connection, job_id: str) -> JobRow | None:
    row = conn.execute("SELECT * FROM jobs WHERE id = ?", (job_id,)).fetchone()
    return _to_jobrow(row) if row else None


# ---- applications ---------------------------------------------------------


def record_application(
    conn: sqlite3.Connection,
    *,
    job_id: str,
    status: str,
    filled_at: str | None = None,
    submitted_at: str | None = None,
    screenshot: str | None = None,
    notes: str | None = None,
) -> None:
    """Insert or update the application for ``job_id``. Idempotent (one per job)."""
    if status not in APP_STATUSES:
        raise ValueError(f"invalid application status: {status!r}")
    conn.execute(
        """INSERT INTO applications (job_id, status, filled_at, submitted_at, screenshot, notes)
           VALUES (?,?,?,?,?,?)
           ON CONFLICT(job_id) DO UPDATE SET
             status=excluded.status,
             filled_at=COALESCE(excluded.filled_at, applications.filled_at),
             submitted_at=COALESCE(excluded.submitted_at, applications.submitted_at),
             screenshot=COALESCE(excluded.screenshot, applications.screenshot),
             notes=COALESCE(excluded.notes, applications.notes)""",
        (job_id, status, filled_at, submitted_at, screenshot, notes),
    )


def application_status(conn: sqlite3.Connection, job_id: str) -> str | None:
    """Return the current application status for ``job_id`` or None if not tracked."""
    row = conn.execute("SELECT status FROM applications WHERE job_id = ?", (job_id,)).fetchone()
    return row["status"] if row else None


# ---- answers cache --------------------------------------------------------


def get_answer(conn: sqlite3.Connection, question_hash: str, company: str) -> str | None:
    """Return a cached answer for (question_hash, company) or None."""
    row = conn.execute(
        "SELECT answer FROM answers WHERE question_hash = ? AND company = ?",
        (question_hash, company),
    ).fetchone()
    return row["answer"] if row else None


def put_answer(
    conn: sqlite3.Connection,
    *,
    question_hash: str,
    company: str,
    question: str,
    answer: str,
    now_iso: str,
    edited: bool = False,
) -> None:
    """Insert or update a cached answer. Sets ``edited_at`` when ``edited`` is True."""
    conn.execute(
        """INSERT INTO answers (question_hash, company, question, answer, created_at, edited_at)
           VALUES (?,?,?,?,?,?)
           ON CONFLICT(question_hash, company) DO UPDATE SET
             answer=excluded.answer,
             edited_at=excluded.edited_at""",
        (question_hash, company, question, answer, now_iso, now_iso if edited else None),
    )
