"""FROZEN interface contract for ATS adapters.

Parallel workstreams (A-D, see SPEC.md §9) implement concrete adapters against
the dataclasses and the ``BaseAdapter`` ABC defined here **without any other
context**. Treat everything in this module as a stable public API:

- Do NOT edit this file from a feature branch. Interface changes go through a
  separate interface PR that all branches rebase on (SPEC.md §9).
- ``detect``, ``extract_form``, and ``fill`` are the only methods a workstream
  implements. ``review_pause`` and ``submit`` are shared, concrete, and must not
  be overridden to auto-click Submit outside the config allowlist path.

A concrete adapter registers itself at import time::

    from autoapply.ats import base

    class MyAdapter(base.BaseAdapter):
        kind = base.ATSKind.LEVER
        ...

    base.register(MyAdapter)

and its module is imported from ``autoapply/ats/__init__.py`` so registration
happens on package import. ``resolve_adapter(url)`` then returns the right class.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import TYPE_CHECKING, ClassVar, Literal

if TYPE_CHECKING:  # pragma: no cover - hints only; Playwright is a runtime dep of adapters.
    from playwright.sync_api import Page


class ATSKind(str, Enum):
    """Applicant Tracking System family a listing URL resolves to."""

    ASHBY = "ashby"
    GREENHOUSE = "greenhouse"
    LEVER = "lever"
    SMARTRECRUITERS = "smartrecruiters"
    RIPPLING = "rippling"
    WORKDAY = "workday"
    ICIMS = "icims"
    GENERIC = "generic"
    MANUAL = "manual"


#: Semantic input type an adapter assigns to a discovered field.
FieldType = Literal[
    "text",
    "email",
    "tel",
    "textarea",
    "select",
    "combobox",
    "multiselect",
    "radio",
    "checkbox",
    "file",
    "date",
    "unknown",
]


@dataclass(slots=True)
class FormField:
    """One input discovered in the DOM by an adapter's :meth:`extract_form`.

    The adapter is responsible for producing a ``selector`` it can later
    re-resolve in :meth:`fill`, and a ``key`` unique within the form used to
    correlate a :class:`FieldPlan` back to this field.
    """

    key: str
    """Stable per-form identifier assigned by the adapter (correlates plan->fill)."""
    field_type: FieldType
    """Semantic input type (drives how the mapper picks a value)."""
    label: str
    """Best human-readable label: ``<label for>`` text, else aria-label/placeholder."""
    selector: str
    """Playwright selector (or serialized locator ref) the adapter can re-resolve."""
    name: str | None = None
    """``input[name]`` attribute, if present."""
    required: bool = False
    """Whether the form marks this field required."""
    options: list[str] = field(default_factory=list)
    """Visible options for select/radio/combobox/multiselect fields."""
    autocomplete: str | None = None
    """``autocomplete`` attribute (e.g. ``given-name``), if present."""
    group: str | None = None
    """Fieldset/section/step label. Used to model multi-step forms."""
    attrs: dict[str, str] = field(default_factory=dict)
    """Extra raw attributes for mapping heuristics: id, data-testid, aria-*, placeholder."""


#: Where a planned value came from. ``unmapped`` => needs human input.
ValueSource = Literal["profile", "answer_cache", "llm", "file", "unmapped"]


@dataclass(slots=True)
class FieldPlan:
    """The mapper's decision for a single :class:`FormField`.

    ``value`` is what should be entered. ``needs_input`` True means the field
    must be visually flagged (red outline) and left for the human — the adapter
    must NOT autofill it.
    """

    field: FormField
    value: str | list[str] | Path | None
    source: ValueSource
    confidence: float
    """0..1 match confidence. Below the config threshold => ``needs_input`` True."""
    needs_input: bool
    """True => red-outline + terminal checklist; do not autofill."""
    note: str = ""
    """Human-facing explanation: which profile key, matched option, or why unmapped."""


@dataclass(slots=True)
class FillPlan:
    """Complete plan for one job's form. Built by :func:`autoapply.filling.mapper.build_plan`.

    Passed to :meth:`BaseAdapter.fill`. The adapter fills every field whose
    :class:`FieldPlan` has ``needs_input`` False and uploads ``resume_path`` to
    file inputs; it flags the rest.
    """

    job_id: str
    job_url: str
    ats: ATSKind
    resume_path: Path | None
    fields: list[FieldPlan]

    @property
    def unresolved(self) -> list[FieldPlan]:
        """Fields the human must handle before submit."""
        return [f for f in self.fields if f.needs_input or f.source == "unmapped"]


#: Terminal state of a fill/submit attempt. Mirrors ``applications.status``.
FillStatus = Literal["filled", "needs_input", "submitted", "failed", "manual", "skipped"]


@dataclass(slots=True)
class FillResult:
    """Outcome of :meth:`BaseAdapter.fill` (and :meth:`submit`)."""

    status: FillStatus
    filled_count: int = 0
    needs_input_labels: list[str] = field(default_factory=list)
    screenshot: Path | None = None
    confirmation_detected: bool = False
    error: str | None = None
    notes: str = ""


class BaseAdapter(ABC):
    """One ATS family.

    Workstreams implement :meth:`detect`, :meth:`extract_form`, and :meth:`fill`
    only. Construct with no required args; keep adapters stateless across jobs.

    SAFETY: :meth:`fill` must never click Submit. Submitting only happens via
    :meth:`submit`, which callers invoke solely when ``--auto-submit`` is set and
    this adapter's :attr:`kind` is on the config allowlist.
    """

    kind: ClassVar[ATSKind]
    """The ATS family this adapter handles. Set on every concrete subclass."""

    @classmethod
    @abstractmethod
    def detect(cls, url: str) -> bool:
        """Return True if this adapter handles ``url`` (host/path match)."""

    @abstractmethod
    def extract_form(self, page: Page) -> list[FormField]:
        """Discover every fillable field on the already-loaded application page.

        The page is navigated to ``job_url`` by the caller before this runs.
        Return an empty list if no application form is present.
        """

    @abstractmethod
    def fill(self, page: Page, plan: FillPlan) -> FillResult:
        """Apply ``plan`` to ``page``.

        Fill each field whose :class:`FieldPlan` has ``needs_input`` False, upload
        ``plan.resume_path`` to file inputs, and red-outline every ``needs_input``
        field. MUST NOT click Submit. Return a :class:`FillResult` with status
        ``"filled"`` when all required fields are satisfied, else ``"needs_input"``
        (populate ``needs_input_labels``), or ``"failed"`` on error.
        """

    # ---- shared, concrete; defined here, not owned by any workstream ----

    def review_pause(self, page: Page, plan: FillPlan, run_dir: Path) -> Path:
        """Screenshot the filled form for the review pause. Returns the path.

        The caller prints the field->value diff and blocks for human input;
        this hook only captures evidence. Adapters generally do not override.
        """
        run_dir.mkdir(parents=True, exist_ok=True)
        shot = run_dir / f"{plan.job_id[:12]}.png"
        page.screenshot(path=str(shot), full_page=True)
        return shot

    #: Confirmation needles checked (lowercased) after a submit click.
    _CONFIRMATION_NEEDLES: ClassVar[tuple[str, ...]] = (
        "thank you for applying",
        "thank you for your application",
        "thank you for your interest",
        "application submitted",
        "application received",
        "application has been received",
        "we have received your application",
        "we've received your application",
        "your application has been submitted",
    )

    def submit(self, page: Page, shot_path: Path | None = None) -> FillResult:
        """Click the form's Submit and PROVE the outcome (SPEC §1).

        Submission is confirmed only on positive evidence: confirmation text, a
        thank-you/confirmation URL, or the application form disappearing. If the
        form is still present with visible validation errors, the click bounced
        — reported as ``needs_input`` (NOT submitted), never as a false success.
        A post-submit screenshot is captured at ``shot_path`` as proof.

        DANGER: only invoked when ``--auto-submit`` is set AND this adapter's
        :attr:`kind` is on the config allowlist. Never call this from :meth:`fill`.
        """
        url_before = page.url
        form = page.locator("form").first
        button = page.locator("button[type=submit], input[type=submit]").first
        try:
            button.click()
            page.wait_for_load_state("networkidle", timeout=15_000)
        except Exception as e:  # noqa: BLE001 - report, never raise mid-run
            return FillResult(status="failed", error=f"submit click failed: {e}")

        page.wait_for_timeout(1_500)  # let confirmation render / errors surface
        if shot_path is not None:
            try:
                page.screenshot(path=str(shot_path), full_page=True)
            except Exception:  # noqa: BLE001 - proof is best-effort
                pass

        html = page.content().lower()
        text_hit = any(n in html for n in self._CONFIRMATION_NEEDLES)
        url_hit = any(w in page.url.lower() for w in ("confirmation", "thank", "submitted"))
        form_gone = False
        try:
            form_gone = form.count() == 0 or not form.is_visible()
        except Exception:  # noqa: BLE001
            form_gone = False

        # Validation errors still on screen => the submit did NOT go through.
        error_visible = False
        try:
            errs = page.locator("[aria-invalid='true'], .field-error, [class*='error']:visible")
            error_visible = errs.count() > 0 and errs.first.is_visible()
        except Exception:  # noqa: BLE001
            error_visible = False

        positive = text_hit or url_hit or (form_gone and page.url != url_before)
        confirmed = positive and not error_visible
        if confirmed:
            why = (
                "confirmation text" if text_hit
                else "confirmation url" if url_hit
                else "form cleared"
            )
            return FillResult(
                status="submitted", confirmation_detected=True, notes=f"submitted — {why}"
            )
        if error_visible:
            return FillResult(
                status="needs_input", confirmation_detected=False,
                notes="submit rejected — validation errors remain; not submitted",
            )
        return FillResult(
            status="filled", confirmation_detected=False,
            notes="submit clicked but no confirmation detected — verify manually",
        )


#: All registered adapter classes, in registration (priority) order.
ADAPTERS: list[type[BaseAdapter]] = []


def register(adapter: type[BaseAdapter]) -> type[BaseAdapter]:
    """Register a concrete adapter so :func:`resolve_adapter` can find it.

    Idempotent. Call at module import time from the adapter's own file — no edit
    to this module is needed to add an adapter. Returns ``adapter`` so it can be
    used as a decorator.
    """
    if adapter not in ADAPTERS:
        ADAPTERS.append(adapter)
    return adapter


def resolve_adapter(url: str) -> type[BaseAdapter] | None:
    """Return the first registered adapter whose ``detect(url)`` is True, else None.

    Callers fall back to the generic adapter when this returns None. Registration
    order is priority order, so register more specific adapters before generic.
    """
    for adapter in ADAPTERS:
        try:
            if adapter.detect(url):
                return adapter
        except Exception:  # noqa: BLE001 - a broken detector must not break resolution
            continue
    return None
